### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NightRaidGamer** [RenardDev/RenJack#2]
How do I get the executable to keep working in its original function?

**Comment by RenardDev** [comment]
```
/noentrypoint - No entry point.
```
This option prevents the entry point from being changed.

**Comment by NightRaidGamer** [comment]
> ```
> /noentrypoint - No entry point.
> ```
> 
> This option prevents the entry point from being changed.

when i use what you said the program works normally but my payload does not work, what is happening?

RenJack64 /verbose:1 /input:putty.exe /maxcodesize:1000000 /payload:beacon.bin /noentrypoint

**Comment by RenardDev** [comment]
Your payload is never called from program code.

**Comment by NightRaidGamer** [comment]
@RenardDev thank's for your time
